source "https://rubygems.org"
gem "mechanize"
gem "settingslogic"
gem "ruby-openid"
gem "rack-openid"

gem "thin"
gem "rails", "3.2.8"
gem "time_diff", "~> 0.2.2"

gem "sqlite3"
gem "sass-rails",   "~> 3.2.3"
gem "coffee-rails", "~> 3.2.1"
gem "uglifier", ">= 1.0.3"
gem "jquery-rails"
