source "https://rubygems.org"
gem "mechanize"
gem "settingslogic"
gem "ruby-openid"
gem "rack-openid"

gem "thin"
gem "rails", "4.0.0"
gem "time_diff"

gem "sqlite3"
gem "sass-rails"
gem "coffee-rails"
gem "uglifier"
gem "jquery-rails"
