defaults: &defaults
  current_version: 2.0
  digest_period: 5 # minutes
  smtp_settings:
    domain: <%= ENV["SMTP_DOMAIN"] %>
    user_name: <%= ENV["SMTP_USER_NAME"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  mail_settings:
    link: <%= ENV["ANNOUNCER_LINK"] %>
    from: <%= ENV["ANNOUNCER_FROM"] %>
    to: <%= ENV["ANNOUNCER_TO"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
